name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/susterdan/alpine-apache2-utils:alpine3.21.3-apache2utils2.4.62
    - name: Push docker image
      run: docker push ghcr.io/susterdan/alpine-apache2-utils:alpine3.21.3-apache2utils2.4.62
